# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-Log
version:      0.21
version_from: lib/DBD/Log.pm
installdirs:  site
requires:
    Class::AccessorMaker:          1
    DBD::Mock:                     1
    DBI:                           1
    IO::File:                      1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
